version: "3.7"

services:
  dockernode:
    image: waltergms/dockernode
    build: .
    ports:
      - 3000:3000
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: objective
      MONGO_INITDB_ROOT_PASSWORD: objpwd
    ports:
      - 27017:27017
